r2013-02-18-tunr/config/routes.rb
R20130218Tunr::Application.routes.draw do
  root :to => 'home#index'

  resources :genres, :artists

  resources :albums do
    member do
      post 'purchase'
    end
  end

  resources :mixtapes do
    member do
      post 'refund'
    end
  end

  resources :songs do
    member do
      get 'purchase'
      post 'buy'
    end
  end

  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

r2013-02-18-tunr/app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  filename   :string(255)
#  artist_id  :integer          default(0)
#  album_id   :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  price      :decimal(, )      default(0.0)
#

class Song < ActiveRecord::Base
  attr_accessible :name, :image, :filename, :genre_ids, :price, :mixtape_ids
  belongs_to :artist
  belongs_to :album
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :mixtapes
  validates :price, :numericality => { :greater_than_or_equal_to => 0}
  #validates :name, :length => { :minimum => 3 }, :uniqueness => true
end

r2013-02-18-tunr/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  image           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#  balance         :decimal(, )      default(0.0)
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :image, :password, :password_confirmation, :balance
  has_many :mixtapes
  has_and_belongs_to_many :albums
  validates :image, :presence => true
  validates :name, :length => { :minimum => 3 }, :uniqueness => true
  validates :balance, :numericality => { :greater_than_or_equal_to => 0}
end

r2013-02-18-tunr/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :check_if_admin, :except => [:index, :show, :purchase, :buy, :refund]
  def index
    @songs = Song.order(:name)
  end
  def new
    @song = Song.new
  end
  def create
    @song = Song.new(params[:song])
    if @song.save
      redirect_to(songs)
    else
      render :new
    end
  end
  def edit
    @song = Song.find(params[:id])
    render :new
  end
  def update
    song = Song.find(params[:id])
    song.update_attributes(params[:song])
    redirect_to(song)
  end
  def destroy
  end
  def show
    @song = Song.find(params[:id])
  end
  def purchase
    @song = Song.find(params[:id])
  end
  def buy
    if params[:song].nil?
      flash[:notice] = "Please assign to a mixtape"
      @song = Song.find(params[:id])
      render :purchase
    else
      song = Song.find(params[:id])
      user = @auth
      user.balance -= song.price
      user.save
      song.update_attributes(params[:song])
      redirect_to(song_path(song.id))
    end
  end
end

r2013-02-18-tunr/app/views/songs/index.html.haml
.row
  .twelve.columns
    = button_to('Add New Song', new_song_path, :method=>:get, :class => 'button radius') if is_admin
    %table
      %th
        Name
      %th
        Image
      - if !@auth.nil?
        %th
          Play Audio
      - if !@auth.nil? && !is_admin
        %th
          Purchase!
      - if is_admin
        %th
          Edit
      - @songs.each do |song|
        %tr{:class => cycle('row0','row1')}
          %td
            = link_to song.name, song, :class => 'button radius tiny'
          %td
            = image_tag(song.image)
          - if !@auth.nil?
            %td
              - if @auth.mixtapes.map(&:songs).flatten.include?(song)
                = audio_tag(song.filename, :controls => true) if @auth != nil
              - else
                .label.alert You need to buy this song to play it!

          - if !@auth.nil? && !is_admin
            %td
              - if @auth.mixtapes.map(&:songs).flatten.include?(song)
                = link_to('Song Purchased!', nil, :class => 'button disabled tiny alert')
              - else
                = link_to('Purchase Song', purchase_song_path(song.id), :method => 'get', :confirm => 'Are you sure?', :class => 'button radius success tiny')
          - if is_admin
            %td
              = link_to 'Edit', edit_song_path(song), :class => "button success tiny" if is_admin

r2013-02-18-tunr/app/views/songs/new.html.haml
.row
  .twelve.columns
    = render(:partial => 'shared/errors', :locals => {:object => @song})
    %h1 Song
    = form_for @song do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :image
      = f.text_field :image
      = f.label :filename
      = f.text_field :filename
      = f.label :price
      = f.text_field :price
      - Genre.find(:all, :order => 'LOWER(name)').each do |genre|
        %span
          = check_box_tag 'song[genre_ids][]', genre.id, genre.in?(@song.genres)
        %span
          = genre.name
        %br
      = f.submit nil, :class => 'button radius'

r2013-02-18-tunr/app/views/songs/purchase.html.haml
.row
  .twelve.columns
    Song Name:
    %div= @song.name
    - @song.mixtapes.each do |mixtape|
      Mixtape Name:
      = mixtape.name
    %br
    Song Cost:
    = number_to_currency(@song.price)
    %br
    Your Balance:
    = number_to_currency(@auth.balance)
    %br
    Balance After Purchase:
    = number_to_currency(@auth.balance - @song.price)
    %br
    Assign it to a Mixtape:
    %br
    Mixtape:
    %br
    - @song.mixtapes.each do |mixtape|
      = mixtape.name
    %br

    %br
    = form_tag buy_song_path, :method => 'post' do |f|
      - @auth.mixtapes.each do |mixtape|
        %span
          = check_box_tag 'song[mixtape_ids][]', mixtape.id, mixtape.in?(@song.mixtapes)
        %span
          = mixtape.name
        %br
      - if number_to_currency(@song.price) <= number_to_currency(@auth.balance)
        = submit_tag 'Purchase', :method => 'post', :confirm => 'Are you sure?', :class => 'button radius success tiny'
      - else
        = link_to('Not Enough Funds', song_path(@song.id), :method => 'get', :class => 'button disabled tiny alert')

r2013-02-18-tunr/app/views/songs/show.html.haml
.row
  .twelve.columns
    %h4
      = "#{@song.name}'s Information:"
      = link_to 'Edit Song', edit_song_path(@song), :class => "button success tiny" if is_admin
    %table
      %tr
        %td
          = audio_tag(@song.filename, :controls => true) if @auth != nil
      %tr{:class => cycle('row0','row1')}
        %td
          = @song.name
      %tr
        %td
          Album:
          = @song.album.present? ? link_to(@song.album.name, @song.album) : 'No albums'
      %tr
        %td
          Artist:
          = @song.artist.present? ? link_to(@song.artist.name, @song.artist) : 'No artist'
      %tr
        %td
          Genre:
          - @song.genres.each do |genre|
            = link_to genre.name, genre
            |
      %tr
        %td
          Mixtape:
          - if @auth.mixtapes.map(&:songs).flatten.include?(@song)
            %br
            - @auth.mixtapes.each do |mixtape|
              %span
                = check_box_tag 'song[mixtape_ids][]', mixtape.id, mixtape.in?(@song.mixtapes)
              %span
                = mixtape.name
          - else
            %span.label Must Purchase to Assign to a Mixtape
          %br
      %tr
        %td
          - if @auth.mixtapes.map(&:songs).flatten.include?(@song)
            = link_to('Refund Song', refund_mixtape_path, :method => 'post', :class => 'button tiny alert')
          - else
            = link_to('Purchase Song', purchase_song_path, :method => 'get', :confirm => 'Are you sure?', :class => 'button radius alert tiny')